wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.12
    start_time: 1650542861
    t:
      1:
      - 1
      - 3
      - 30
      - 53
      - 55
      3:
      - 16
      4: 3.7.12
      5: 0.12.14
      8:
      - 5
agent_visible:
  desc: null
  value: 1
aggregator_type:
  desc: null
  value: sum
attention_type:
  desc: null
  value: general
bs:
  desc: null
  value: 60000
capture_reward:
  desc: null
  value: 10
center_adv:
  desc: null
  value: 1
clip_grad_norm:
  desc: null
  value: 7
discount:
  desc: null
  value: 0.99
embedding_dim:
  desc: null
  value: 64
encoder_hidden_sizes:
  desc: null
  value:
  - 128
ent:
  desc: null
  value: 0.1
entropy_method:
  desc: null
  value: regularized
eval_during_training:
  desc: null
  value: 0
eval_epoch_freq:
  desc: null
  value: 5
eval_greedy:
  desc: null
  value: 1
exp_name:
  desc: null
  value: null
gae_lambda:
  desc: null
  value: 0.97
gcn_bias:
  desc: null
  value: 1
grid_size:
  desc: null
  value: 10
hidden_nonlinearity:
  desc: null
  value: tanh
inspect_steps:
  desc: null
  value: 0
loc:
  desc: null
  value: local
max_env_steps:
  desc: null
  value: 200
mode:
  desc: null
  value: train
n_agents:
  desc: null
  value: 8
n_envs:
  desc: null
  value: 1
n_epochs:
  desc: null
  value: 1000
n_eval_episodes:
  desc: null
  value: 100
n_gcn_layers:
  desc: null
  value: 2
n_preys:
  desc: null
  value: 8
opt_mini_epochs:
  desc: null
  value: 10
opt_n_minibatches:
  desc: null
  value: 3
penalty:
  desc: null
  value: -1.0
policy_hidden_sizes:
  desc: null
  value:
  - 128
  - 64
  - 32
positive_adv:
  desc: null
  value: 0
render:
  desc: null
  value: 1
residual:
  desc: null
  value: 1
run_id:
  desc: null
  value: 0
seed:
  desc: null
  value: 1
step_cost:
  desc: null
  value: -0.1
